version: "2"

#docker network create turma1

networks:
  sisu:
    name: sisu

  caddy:
    external: true
    name: caddy

#volumes:
#  st1_disk:
#    driver: local

services:
  fastapi:
    image: estudo/fastapi:0.0.1 
    container_name: fastapi
    command: "uvicorn app.main:app --reload --host 0.0.0.0 --port 7010"
    restart: always
    environment:
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
    volumes:
      - .:/app
    ports:
      - 7010:7010
    networks:
      - sisu
      - caddy
  

